version: '3.8'

services:
  sparktts:
    image: "sparktts:v0.1.0"
    ports:
      - "8887:8887"
    volumes:
      - ./example:/app/example
    environment:
      - MODEL_DIR=/app/pretrained_models
      - ENV_NAME=sparktts
    restart: always
    container_name: spark_tts_server